
x-common-other: &other
  mc:
    image: minio/mc
    container_name: mc
    <<: *common
    restart: "no"
    depends_on:
      - minio
    labels:
      traefik.enable: false

  archive-warrior:
    container_name: warrior
    image: atdr.meo.ws/archiveteam/warrior-dockerfile
    hostname: warrior.${DOMAIN}
    <<: *common
    environment:
      <<: *env-vars
      SELECTED_PROJECT: auto
      DOWNLOADER: pyxxil
    dns:
      - 1.1.1.1
      - 9.9.9.9
    labels:
      traefik.port: 8001
      traefik.http.services.warrior.loadbalancer.server.port: 8001
      traefik.http.routers.warrior.entrypoints: websecure
      traefik.http.routers.warrior.tls: true
      traefik.http.routers.warrior.tls.certResolver: letsencrypt
      diun.enable: false

