x-common-env-variables: &env-vars
  PUID: ${PUID}
  PGID: ${PGID}
  TZ: ${TIMEZONE}

x-common-driver-variables: &driver-opts
  type: none
  o: bind

x-common-healthcheck-variables: &healthcheck
  interval: 60s
  timeout: 10s
  retries: 3
  start_period: 30s
  start_interval: 15s

x-common-networks: &networks
  networks:
    - frontend
    - backend

x-common-logging: &logging
  logging:
    driver: local
    options:
      compress: "true"
      max-size: "10m"
      max-file: "3"

x-common-common: &common
  <<: [*networks, *logging]
  restart: unless-stopped
  environment: *env-vars

networks:
  frontend:
    name: frontend
    external: false
    enable_ipv6: true
    ipam:
      config:
        - subnet: fd00::/112
        - subnet: 172.20.0.0/14
  backend:
    name: backend
    external: false
    internal: true

volumes:
  config-adguard:
    driver_opts:
      <<: *driver-opts
      device: ${CONFIG_DIR}/adguard
  config-adguardhome-sync:
    driver_opts:
      <<: *driver-opts
      device: ${CONFIG_DIR}/adguardhome-sync
  config-authelia:
    driver_opts:
      <<: *driver-opts
      device: ${CONFIG_DIR}/authelia
  config-beets:
    driver_opts:
      <<: *driver-opts
      device: ${CONFIG_DIR}/beets
  config-bookmarks:
    driver_opts:
      <<: *driver-opts
      device: ${CONFIG_DIR}/bookmarks
  config-freshrss:
    driver_opts:
      <<: *driver-opts
      device: ${CONFIG_DIR}/freshrss
  config-frigate:
    driver_opts:
      <<: *driver-opts
      device: ${CONFIG_DIR}/frigate
  config-grafana:
    driver_opts:
      <<: *driver-opts
      device: ${CONFIG_DIR}/grafana/config
  config-grafana-data:
    driver_opts:
      <<: *driver-opts
      device: ${CONFIG_DIR}/grafana/data
  config-grafana-home:
    driver_opts:
      <<: *driver-opts
      device: ${CONFIG_DIR}/grafana/home
  config-home-assistant:
    driver_opts:
      <<: *driver-opts
      device: ${CONFIG_DIR}/homeassistant
  config-immich:
    driver_opts:
      <<: *driver-opts
      device: ${CONFIG_DIR}/immich
  config-jellyfin:
    driver_opts:
      <<: *driver-opts
      device: ${CONFIG_DIR}/jellyfin
  config-jellyfin-cache:
    driver_opts:
      <<: *driver-opts
      device: ${CONFIG_DIR}/jellyfin/cache
  config-jellyseerr:
    driver_opts:
      <<: *driver-opts
      device: ${CONFIG_DIR}/jellyseerr
  config-ldap:
    driver_opts:
      <<: *driver-opts
      device: ${CONFIG_DIR}/ldap/config
  config-ldap-db:
    driver_opts:
      <<: *driver-opts
      device: ${CONFIG_DIR}/ldap/db
  config-matter:
    driver_opts:
      <<: *driver-opts
      device: ${CONFIG_DIR}/matter
  config-mosquitto:
    driver_opts:
      <<: *driver-opts
      device: ${CONFIG_DIR}/mqtt
  config-ntfy:
    driver_opts:
      <<: *driver-opts
      device: ${CONFIG_DIR}/ntfy/config
  config-ntfy-cache:
    driver_opts:
      <<: *driver-opts
      device: ${CONFIG_DIR}/ntfy/cache
  config-s3:
    driver_opts:
      <<: *driver-opts
      device: ${CONFIG_DIR}/s3
  config-pg-vectors:
    driver_opts:
      <<: *driver-opts
      device: ${CONFIG_DIR}/pg-vectors
  config-piper:
    driver_opts:
      <<: *driver-opts
      device: ${CONFIG_DIR}/piper
  config-podgrab:
    driver_opts:
      <<: *driver-opts
      device: ${CONFIG_DIR}/podgrab/config
  config-postgres:
    driver_opts:
      <<: *driver-opts
      device: ${CONFIG_DIR}/postgres
  config-prometheus:
    driver_opts:
      <<: *driver-opts
      device: ${CONFIG_DIR}/prometheus
  config-prowlarr:
    driver_opts:
      <<: *driver-opts
      device: ${CONFIG_DIR}/prowlarr
  config-qbittorrent:
    driver_opts:
      <<: *driver-opts
      device: ${CONFIG_DIR}/qbittorrent
  config-qbittorrent-manage:
    driver_opts:
      <<: *driver-opts
      device: ${CONFIG_DIR}/qbittorrent-manage
  config-radarr:
    driver_opts:
      <<: *driver-opts
      device: ${CONFIG_DIR}/radarr
  config-readarr:
    driver_opts:
      <<: *driver-opts
      device: ${CONFIG_DIR}/readarr
  config-recyclarr:
    driver_opts:
      <<: *driver-opts
      device: ${CONFIG_DIR}/recyclarr
  config-redis:
    driver_opts:
      <<: *driver-opts
      device: ${CONFIG_DIR}/redis
  config-scripts:
    driver_opts:
      <<: *driver-opts
      device: ${CONFIG_DIR}/scripts
  config-sonarr:
    driver_opts:
      <<: *driver-opts
      device: ${CONFIG_DIR}/sonarr
  config-speedtest:
    driver_opts:
      <<: *driver-opts
      device: ${CONFIG_DIR}/speedtest
  config-syncthing:
    driver_opts:
      <<: *driver-opts
      device: ${CONFIG_DIR}/syncthing
  config-title:
    driver_opts:
      <<: *driver-opts
      device: ${CONFIG_DIR}/title-maker
  config-title-logs:
    driver_opts:
      <<: *driver-opts
      device: ${CONFIG_DIR}/title-maker/logs
  config-traefik:
    driver_opts:
      <<: *driver-opts
      device: ${CONFIG_DIR}/traefik
  config-vaultwarden:
    driver_opts:
      <<: *driver-opts
      device: ${CONFIG_DIR}/vaultwarden
  config-vikunja:
    driver_opts:
      <<: *driver-opts
      device: ${CONFIG_DIR}/vikunja
  config-vikunja-conf:
    driver_opts:
      <<: *driver-opts
      device: ${CONFIG_DIR}/vikunja-config
  downloads:
    driver_opts:
      <<: *driver-opts
      device: ${DOWNLOAD_DIR}
  downloads-music:
    driver_opts:
      <<: *driver-opts
      device: ${DOWNLOAD_DIR}/Music
  media:
    driver_opts:
      <<: *driver-opts
      device: ${DATA_DIR}
  media-books:
    driver_opts:
      <<: *driver-opts
      device: ${DATA_DIR}/Books
  media-camera:
    driver_opts:
      <<: *driver-opts
      device: ${DATA_DIR}/Camera
  media-movies:
    driver_opts:
      <<: *driver-opts
      device: ${DATA_DIR}/Movies
  media-music:
    driver_opts:
      <<: *driver-opts
      device: ${DATA_DIR}/Music
  media-photos:
    driver_opts:
      <<: *driver-opts
      device: ${DATA_DIR}/Photos
  media-podcasts:
    driver_opts:
      <<: *driver-opts
      device: ${DATA_DIR}/Podcasts
  media-shows:
    driver_opts:
      <<: *driver-opts
      device: ${DATA_DIR}/Television Shows
  media-youtube:
    driver_opts:
      <<: *driver-opts
      device: ${DATA_DIR}/Youtube
  sync:
    driver_opts:
      <<: *driver-opts
      device: ${SYNC_DIR}

