x-common-admin: &admin
  traefik:
    container_name: dash
    image: traefik
    <<: *common
    networks:
      - web
    command:
      - --accesslog=true
      - --accesslog.addinternals
      - --accesslog.bufferingsize=100
      - --accesslog.format=json
      - --accesslog.filters.statuscodes=200,300-302
      - --accesslog.filters.retryattempts
      - --accesslog.filters.minduration=10ms
      - --api=true
      - --api.dashboard=true
      - --certificatesresolvers.letsencrypt.acme.caserver=https://acme-v02.api.letsencrypt.org/directory
      - --certificatesresolvers.letsencrypt.acme.dnschallenge.delaybeforecheck=0
      - --certificatesresolvers.letsencrypt.acme.dnschallenge.provider=cloudflare
      - --certificatesresolvers.letsencrypt.acme.dnschallenge.resolvers=1.1.1.1:53,8.8.8.8:53,9.9.9.9:53
      - --certificatesresolvers.letsencrypt.acme.email=${ADMIN_EMAIL}
      - --certificatesresolvers.letsencrypt.acme.storage=/config/acme.json
      - --entrypoints.web.address=:80
      - --entrypoints.web.forwardedHeaders.insecure=false
      - --entrypoints.web.proxyProtocol.insecure=false
      - --entrypoints.web.forwardedHeaders.trustedIPs=${TRUSTED_IPS}
      - --entrypoints.web.proxyProtocol.trustedIPs=${TRUSTED_IPS}
      - --entrypoints.web.http.redirections.entryPoint.to=websecure
      - --entrypoints.web.http.redirections.entryPoint.scheme=https
      - --entrypoints.web.http.redirections.entrypoint.permanent=true
      - --entrypoints.websecure.address=:443
      - --entrypoints.websecure.http.middlewares=compress@file
      - --entrypoints.websecure.http.tls.certResolver=letsencrypt
      - --entrypoints.websecure.http.tls.domains[0].main=${DOMAIN}
      - --entrypoints.websecure.http.tls.domains[0].sans=*.${DOMAIN}
      - --entrypoints.websecure.http3
      - --entrypoints.websecure.http3.advertisedport=443
      - --entryPoints.websecure.forwardedHeaders.trustedIPs=${TRUSTED_IPS}
      - --entryPoints.websecure.proxyProtocol.trustedIPs=${TRUSTED_IPS}
      - --entrypoints.websecure.forwardedHeaders.insecure=false
      - --entrypoints.websecure.proxyProtocol.insecure=false
      - --log.compress=true
      - --log.format=json
      - --log.level=info
      - --ping=true
      - --metrics.prometheus=true
      - --metrics.prometheus.addServicesLabels=true
      - --metrics.prometheus.addrouterslabels=true
      - --metrics.prometheus.addEntryPointsLabels=true
      - --metrics.addinternals
      - --providers.docker.defaultRule=Host(`{{ .ContainerName }}.${DOMAIN}`)
      - --providers.docker=true
      - --providers.docker.watch=true
      - --providers.docker.exposedbydefault=true
      - --providers.docker.network=web
      - --providers.file.directory=/config
    environment:
      <<: *env-vars
      CLOUDFLARE_DNS_API_TOKEN: ${CLOUDFLARE_DNS_API_TOKEN}
    ports:
      - 0.0.0.0:80:80
      - 0.0.0.0:443:443/udp
      - 0.0.0.0:443:443/tcp
      - ":::80:80"
      - ":::443:443/udp"
      - ":::443:443/tcp"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - config-traefik:/config
    healthcheck:
      test: ["CMD", "traefik", "healthcheck", "--ping"]
      <<: *healthcheck
    depends_on:
      - auth
    labels:
      traefik.http.routers.dashboard.rule: Host(`dash.${DOMAIN}`)
      traefik.http.routers.dashboard.service: api@internal
      traefik.http.routers.dashboard.middlewares: auth@file
      traefik.http.routers.dashboard.tls: true
      traefik.http.routers.dashboard.tls.certResolver: letsencrypt
      traefik.http.routers.dashboard.entrypoints: websecure

  whoami:
    image: traefik/whoami
    container_name: whoami
    <<: *common

  auth:
    image: authelia/authelia
    container_name: auth
    <<: *common
    depends_on:
      - ldap
    volumes:
      - config-authelia:/config
    labels:
      traefik.http.services.auth.loadbalancer.server.port: 9091
      traefik.http.routers.auth.entrypoints: websecure
      traefik.http.routers.auth.tls: true
      traefik.http.routers.auth.tls.certResolver: letsencrypt
      traefik.http.middlewares.cors.headers.accesscontrolalloworiginlistregex: https://[a-z]+.${DOMAIN}
      traefik.http.routers.auth.middlewares: cors

  ldap:
    image: osixia/openldap
    container_name: ldap
    hostname: ldap.${DOMAIN}
    restart: always
    <<: *logging
    networks:
      - internal
    volumes:
      - config-ldap-db:/var/lib/ldap
      - config-ldap:/etc/ldap/slapd.d
    ports:
      - ${IP}:389:389
      - ${IP}:636:636
    healthcheck:
      test: ["CMD-SHELL", "ldapsearch -Y EXTERNAL -H ldapi:/// | grep -i 'numresponses' || exit 1"]
      <<: *healthcheck
    environment:
      <<: *env-vars
      LDAP_ORGANISATION: ${ORGANISATION}
      LDAP_DOMAIN: ${DOMAIN}
      LDAP_BASE_DN: dc=${DC_DOMAIN},dc=${TLD}
      LDAP_RFC2307BIS_SCHEMA: true
      LDAP_ADMIN_PASSWORD: ${LDAP_PASSWORD}
      LDAP_READONLY_USER: false
      LDAP_TLS: true
      LDAP_TLS_VERIFY_CLIENT: 'never'
    labels:
      traefik.enable: false

  ldap-user-manager:
    image: wheelybird/ldap-user-manager
    container_name: account
    <<: *common
    depends_on:
      - ldap
    healthcheck:
      test: ["CMD-SHELL", "curl --fail localhost:80"]
      <<: *healthcheck
    environment:
      <<: *env-vars
      SERVER_HOSTNAME: account.${DOMAIN}
      ORGANISATION_NAME: ${ORGANISATION}
      LDAP_URI: "ldaps://ldap"
      LDAP_BASE_DN: dc=${DC_DOMAIN},dc=${TLD}
      LDAP_ADMINS_GROUP: "admins"
      LDAP_ADMIN_BIND_DN: "cn=admin,dc=${DC_DOMAIN},dc=${TLD}"
      LDAP_ADMIN_BIND_PWD: ${LDAP_PASSWORD}
      LDAP_USES_NIS_SCHEMA: false
      LDAP_REQUIRE_STARTTLS: false
      LDAP_IGNORE_CERT_ERRORS: true
      LDAP_DEBUG: true
      NO_HTTPS: true
      SMTP_LOG_LEVEL: 3
      SMTP_HOSTNAME: ${SMTP_HOST}
      SMTP_HOST_PORT: 25
      SMTP_USE_TLS: true
      SMTP_USERNAME: ${SMTP_USER}
      SMTP_PASSWORD: ${SMTP_PASS}
      EMAIL_FROM_ADDRESS: account@${DOMAIN}
      EMAIL_DOMAIN: ${DOMAIN}
    labels:
      traefik.http.services.ldap-user-manager.loadbalancer.server.port: 80
      traefik.http.routers.ldap-user-manager.entrypoints: websecure
      traefik.http.routers.ldap-user-manager.tls: true
      traefik.http.routers.ldap-user-manager.tls.certResolver: letsencrypt

  ntfy:
    image: binwiederhier/ntfy
    container_name: ntfy
    <<: *common
    command:
      - serve
    volumes:
      - config-ntfy-cache:/var/cache/ntfy
      - config-ntfy:/etc/ntfy
    healthcheck:
      test: ["CMD-SHELL", "wget -q --tries=1 http://localhost:80/v1/health -O - | grep -Eo '\"healthy\"\\s*:\\s*true' || exit 1"]
      <<: *healthcheck
    labels:
      traefik.http.routers.ntfy.entrypoints: websecure
      traefik.http.services.ntfy.loadbalancer.server.port: 80
      traefik.http.routers.ntfy.tls: true
      traefik.http.routers.ntfy.tls.certresolver: letsencrypt

