x-common-admin: &admin
  traefik:
    container_name: dash
    image: traefik
    <<: *common
    command:
      - --accesslog=true
      - --accesslog.format=json
      - --accesslog.filters.statuscodes=200,300-302
      - --accesslog.filters.retryattempts
      - --accesslog.filters.minduration=10ms
      - --api=true
      - --api.dashboard=true
      - --certificatesresolvers.letsencrypt.acme.caserver=https://acme-v02.api.letsencrypt.org/directory
      - --certificatesresolvers.letsencrypt.acme.dnschallenge.delaybeforecheck=0
      - --certificatesresolvers.letsencrypt.acme.dnschallenge.provider=cloudflare
      - --certificatesresolvers.letsencrypt.acme.dnschallenge.resolvers=1.1.1.1:53,8.8.8.8:53
      - --certificatesresolvers.letsencrypt.acme.email=${ADMIN_EMAIL}
      - --certificatesresolvers.letsencrypt.acme.storage=/config/acme.json
      - --entrypoints.web.address=:80
      - --entrypoints.web.forwardedHeaders.insecure=false
      - --entrypoints.web.proxyProtocol.insecure=false
      - --entryPoints.web.forwardedHeaders.trustedIPs=10.0.0.0/8,172.0.0.0/8,192.168.0.0/16,fc00::/7,100.0.0.0/8
      - --entryPoints.web.proxyProtocol.trustedIPs=10.0.0.0/8,172.0.0.0/8,192.168.0.0/16,fc00::/7,100.0.0.0/8
      - --entrypoints.websecure.address=:443
      - --entrypoints.websecure.http3
      - --entrypoints.websecure.http.tls.certResolver=letsencrypt
      - --entrypoints.websecure.http.tls.domains[0].main=${DOMAIN}
      - --entrypoints.websecure.http.tls.domains[0].sans=*.${DOMAIN}
      - --entryPoints.websecure.forwardedHeaders.trustedIPs=10.0.0.0/8,172.0.0.0/8,192.168.0.0/16,fc00::/7,100.0.0.0/8
      - --entryPoints.websecure.proxyProtocol.trustedIPs=10.0.0.0/8,172.0.0.0/8,192.168.0.0/16,fc00::/7,100.0.0.0/8
      - --entrypoints.websecure.forwardedHeaders.insecure=false
      - --entrypoints.websecure.proxyProtocol.insecure=false
      - --experimental.http3=true
      - --log.level=info
      - --ping=true
      - --metrics.prometheus=true
      - --metrics.prometheus.addServicesLabels=true
      - --metrics.prometheus.addrouterslabels=true
      - --metrics.prometheus.addEntryPointsLabels=true
      - --providers.docker.defaultRule=Host(`{{ .ContainerName }}.${DOMAIN}`)
      - --providers.docker=true
      - --providers.docker.watch=true
      - --providers.docker.exposedbydefault=true
      - --providers.docker.network=web
      - --providers.file.directory=/config
      - --tracing=true
      - --tracing.jaeger=true
      - --tracing.jaeger.samplingServerURL=http://tracing:5778/sampling
      - --tracing.jaeger.localAgentHostPort=tracing:6831
      - --tracing.jaeger.collector.endpoint=http://tracing:14268/api/traces?format=jaeger.thrift
    environment:
      <<: *env-vars
      CLOUDFLARE_DNS_API_TOKEN: ${CLOUDFLARE_DNS_API_TOKEN}
      OTEL_SERVICE_NAME: traefik
    ports:
      - 80:80
      - 443:443/tcp
      - 443:443/udp
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - config-traefik:/config
    networks:
      internal:
      web:
        priority: 20
        aliases:
          - auth.${DOMAIN}
      private_network:
    healthcheck:
      test: ["CMD", "traefik", "healthcheck", "--ping"]
      interval: 30s
      timeout: 3s
      retries: 3
    depends_on:
      - auth
    labels:
      traefik.http.routers.dashboard.rule: Host(`dash.${DOMAIN}`)
      traefik.http.middlewares.auth.forwardauth.address: http://auth:9091/api/verify?rd=https://auth.${DOMAIN}
      traefik.http.middlewares.auth.forwardauth.trustForwardHeader: true
      traefik.http.middlewares.auth.forwardauth.authResponseHeaders: Remote-User,Remote-Groups,Remote-Name,Remote-Email
      traefik.http.routers.dashboard.service: api@internal
      traefik.http.routers.dashboard.middlewares: auth
      traefik.http.routers.dashboard.tls: true
      traefik.http.routers.dashboard.tls.certResolver: letsencrypt
      traefik.http.routers.dashboard.entrypoints: websecure
      traefik.http.routers.http-catchall.rule: hostregexp(`{host:.+}`)
      traefik.http.routers.http-catchall.entrypoints: web
      traefik.http.routers.http-catchall.middlewares: redirect-to-https
      traefik.http.middlewares.redirect-to-https.redirectscheme.scheme: https
      traefik.http.middlewares.redirect-to-https.redirectScheme.permanent: true

  auth:
    image: authelia/authelia
    container_name: auth
    <<: *common
    depends_on:
      - ldap
    volumes:
      - config-authelia:/config
    labels:
      traefik.http.services.auth.loadbalancer.server.port: 9091
      traefik.http.routers.auth.entrypoints: websecure
      traefik.http.routers.auth.tls: true
      traefik.http.routers.auth.tls.certResolver: letsencrypt

  ldap:
    image: osixia/openldap
    container_name: ldap
    hostname: ldap.${DOMAIN}
    <<: *common
    volumes:
      - config-ldap-db:/var/lib/ldap
      - config-ldap:/etc/ldap/slapd.d
    ports:
      - 389:389
      - 636:636
    healthcheck:
      test: ["CMD-SHELL", "ldapsearch -Y EXTERNAL -H ldapi:/// | grep -i 'numresponses' || exit 1"]
      interval: 60s
      timeout: 10s
      retries: 3
      start_period: 40s
    environment:
      <<: *env-vars
      LDAP_ORGANISATION: ${ORGANISATION}
      LDAP_DOMAIN: ${DOMAIN}
      LDAP_BASE_DN: dc=${DC_DOMAIN},dc=${TLD}
      LDAP_RFC2307BIS_SCHEMA: true
      LDAP_ADMIN_PASSWORD: ${LDAP_PASSWORD}
      LDAP_READONLY_USER: false
      LDAP_TLS: true
      LDAP_TLS_VERIFY_CLIENT: 'never'
    labels:
      traefik.enable: false

  ldap-user-manager:
    image: wheelybird/ldap-user-manager
    container_name: account
    <<: *common
    depends_on:
      - ldap
    healthcheck:
      test: ["CMD-SHELL", "curl --fail localhost:80"]
      interval: 60s
      timeout: 10s
      retries: 3
      start_period: 40s
    environment:
      <<: *env-vars
      SERVER_HOSTNAME: account.${DOMAIN}
      ORGANISATION_NAME: ${ORGANISATION}
      LDAP_URI: "ldaps://ldap"
      LDAP_BASE_DN: dc=${DC_DOMAIN},dc=${TLD}
      LDAP_ADMINS_GROUP: "admins"
      LDAP_ADMIN_BIND_DN: "cn=admin,dc=${DC_DOMAIN},dc=${TLD}"
      LDAP_ADMIN_BIND_PWD: ${LDAP_PASSWORD}
      LDAP_USES_NIS_SCHEMA: false
      LDAP_REQUIRE_STARTTLS: false
      LDAP_IGNORE_CERT_ERRORS: true
      LDAP_DEBUG: true
      NO_HTTPS: true
      SMTP_LOG_LEVEL: 3
      SMTP_HOSTNAME: ${SMTP_HOST}
      SMTP_HOST_PORT: 25
      SMTP_USE_TLS: true
      SMTP_USERNAME: ${SMTP_USER}
      SMTP_PASSWORD: ${SMTP_PASS}
      EMAIL_FROM_ADDRESS: account@${DOMAIN}
      EMAIL_DOMAIN: ${DOMAIN}
    labels:
      traefik.http.services.ldap-user-manager.loadbalancer.server.port: 80
      traefik.http.routers.ldap-user-manager.entrypoints: websecure
      traefik.http.routers.ldap-user-manager.tls: true
      traefik.http.routers.ldap-user-manager.tls.certResolver: letsencrypt

  mailrise:
    image: yoryan/mailrise
    container_name: mailrise
    restart: unless-stopped
    command: "-vv /config/mailrise.conf"
    volumes:
      - config-mailrise:/config:ro
    <<: *common
    environment:
      <<: *env-vars
      AWS_URL: ses://${AWS_SES_URL}
    ports:
      - 465:465
      - 8025:8025
    labels:
      traefik.tcp.routers.mailrise.rule: HostSNI(`${DOMAIN}`)
      traefik.tcp.routers.mailrise.tls: true
      traefik.tcp.routers.mailrise.tls.certresolver: letsencrypt
      traefik.tcp.routers.mailrise.entrypoints: websecure

  diun:
    image: crazymax/diun
    container_name: diun
    command: serve
    hostname: diun.${DOMAIN}
    <<: *common
    volumes:
      - config-diun:/data
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      <<: *env-vars
      DIUN_WATCH_SCHEDULE: 0 */12 * * *
      DIUN_PROVIDERS_DOCKER: true
      DIUN_PROVIDERS_DOCKER_WATCHBYDEFAULT: true
      DIUN_NOTIF_NTFY_ENDPOINT: http://ntfy
      DIUN_NOTIF_NTFY_TOPIC: server
      DIUN_WATCH_RUNONSTARTUP: true
    labels:
      traefik.enable: false

  ntfy:
    image: binwiederhier/ntfy
    container_name: ntfy
    <<: *common
    command:
      - serve
    volumes:
      - config-ntfy-cache:/var/cache/ntfy
      - config-ntfy:/etc/ntfy
    healthcheck:
      test: ["CMD-SHELL", "wget -q --tries=1 http://localhost:80/v1/health -O - | grep -Eo '\"healthy\"\\s*:\\s*true' || exit 1"]
      interval: 60s
      timeout: 10s
      retries: 3
      start_period: 40s
    labels:
      traefik.http.routers.ntfy.entrypoints: websecure
      traefik.http.services.ntfy.loadbalancer.server.port: 80
      traefik.http.routers.ntfy.tls: true
      traefik.http.routers.ntfy.tls.certresolver: letsencrypt

  alerting:
    container_name: alerts
    image: saibe1111/grafana-to-ntfy
    <<: *common
    environment:
      <<: *env-vars
      NTFY_TOPIC: server
      NTFY_SERVER: http://ntfy
    labels:
      traefik.enable: false

