x-common-metrics: &metrics
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    <<: *common
    entrypoint: ["/bin/sh", "-c"]
    command:
      - "rm -rf /prometheus/data/chunks_head; /bin/prometheus
        --config.file=/etc/prometheus/prometheus.yml
        --storage.tsdb.path=/prometheus"
    volumes:
      - config-prometheus:/etc/prometheus
    healthcheck:
      test: ["CMD-SHELL", "wget --spider http://localhost:9090 || exit 1"]
      interval: 10s
      timeout: 15s
      retries: 10
      start_period: 40s
    labels:
      traefik.http.routers.prometheus.entrypoints: websecure
      traefik.http.services.prometheus.loadbalancer.server.port: 9090
      traefik.http.routers.prometheus.tls: true
      traefik.http.routers.prometheus.tls.certResolver: letsencrypt
      traefik.http.routers.prometheus.middlewares: auth@file
      traefik.backend: prometheus

  grafana:
    image: grafana/grafana
    container_name: metrics
    hostname: metrics.${DOMAIN}
    <<: *common
    user: ${PUID}
    environment:
      <<: *env-vars
      GF_SERVER_ROOT_URL: https://metrics.${DOMAIN}
      OTEL_SERVICE_NAME: grafana
    volumes:
      - config-grafana:/etc/grafana
      - config-grafana-data:/var/lib/grafana
    healthcheck:
      test: ["CMD-SHELL", "curl http://localhost:3000/healthz | grep -i 'ok' || exit 1"]
      interval: 10s
      timeout: 15s
      retries: 10
      start_period: 40s
    labels:
      traefik.http.services.grafana.loadBalancer.server.port: 3000
      traefik.http.routers.grafana.entrypoints: websecure
      traefik.http.routers.grafana.tls: true
      traefik.http.routers.grafana.tls.certResolver: letsencrypt

  loki:
    container_name: loki
    image: grafana/loki
    <<: *common
    command: -config.file=/etc/loki/loki-config.yaml
    volumes:
      - config-loki:/etc/loki
      - config-loki-data:/loki
    depends_on:
      - redis
      - minio
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--no-verbose",
          "--tries=1",
          "--spider",
          "http://localhost:3100/ready",
        ]
      interval: 10s
      timeout: 15s
      retries: 10
      start_period: 40s
    labels:
      traefik.enable: false

  promtail:
    container_name: logs
    image: grafana/promtail
    <<: *common
    command: -config.file=/etc/promtail/promtail-config.yaml
    volumes:
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - config-promtail:/etc/promtail
    depends_on:
      - loki
    labels:
      traefik.http.services.promtail.loadBalancer.server.port: 9080
      traefik.http.routers.promtail.entrypoints: websecure
      traefik.http.routers.promtail.tls: true
      traefik.http.routers.promtail.tls.certResolver: letsencrypt
      traefik.http.routers.promtail.middlewares: auth@file

  adguard_exporter:
    image: ebrianne/adguard-exporter
    container_name: adguard-exporter
    <<: *common
    environment:
      adguard_protocol: http
      adguard_hostname: 192.168.1.1
      adguard_username: ${ADGUARD_USERNAME}
      adguard_password: ${ADGUARD_PASSWORD}
      adguard_port: 81
      server_port: 9617
      interval: 10s
      log_limit: 10000
    labels:
      traefik.enable: false

  node_exporter:
    image: quay.io/prometheus/node-exporter
    container_name: host
    command: --path.rootfs=/host
    <<: *common
    pid: host
    volumes:
      - /:/host:ro,rslave
    healthcheck:
      test: ["CMD-SHELL", "/bin/netstat -pant | /bin/grep ':9100'"]
      interval: 45s
      timeout: 30s
      retries: 3
    labels:
      traefik.enable: false

  postgres-exporter:
    image: quay.io/prometheuscommunity/postgres-exporter
    container_name: postgres-exporter
    <<: *common
    depends_on:
      - postgres
    networks:
      - internal
    environment:
      <<: *env-vars
      DATA_SOURCE_NAME: "postgresql://${DATABASE_USERNAME}:${DATABASE_PASSWORD}@postgres?sslmode=disable,postgresql://immich:${DATABASE_PASSWORD}@pg-vectors?sslmode=disable"
      DATA_SOURCE_USER: ${DATABASE_USERNAME}
      DATA_SOURCE_PASS: ${DATABASE_PASSWORD}
      PG_EXPORTER_AUTO_DISCOVER_DATABASES: true
    labels:
      traefik.enable: false

  smokeping:
    image: lscr.io/linuxserver/smokeping:latest
    container_name: smokeping
    <<: *common
    environment:
      <<: *env-vars
      MASTER_URL: https://smokeping.${DOMAIN}/smokeping/
      CACHE_DIR: /tmp
    volumes:
      - config-smokeping:/config
      - config-smokeping-data:/data
    labels:
      traefik.http.services.smokeping.loadBalancer.server.port: 80
      traefik.http.routers.smokeping.entrypoints: websecure
      traefik.http.routers.smokeping.tls: true
      traefik.http.routers.smokeping.tls.certResolver: letsencrypt
      traefik.http.routers.smokeping.middlewares: auth@file
