x-common-dns: &dns  
  letsblockit:
    image: ghcr.io/letsblockit/server
    container_name: letsblockit
    hostname: letsblockit.${DOMAIN}
    <<: *common
    depends_on:
      - postgres
    environment:
      <<: *env-vars
      LETSBLOCKIT_DATABASE_URL: postgresql://${DATABASE_USERNAME}:${DATABASE_PASSWORD}@postgres:5432/letsblockit
      LETSBLOCKIT_AUTH_METHOD: proxy
      LETSBLOCKIT_AUTH_PROXY_HEADER_NAME: Remote-User
    labels:
      traefik.http.services.letsblockit.loadbalancer.server.port: 8765
      traefik.http.routers.letsblockit.entrypoints: websecure
      traefik.http.routers.letsblockit.tls: true
      traefik.http.routers.letsblockit.tls.certResolver: letsencrypt
      traefik.http.routers.letsblockit.middlewares: auth@file

  adguard:
    container_name: adguard
    image: adguard/adguardhome
    <<: *common
    restart: always
    volumes:
      - config-adguard:/opt/adguardhome/conf
    labels:
      traefik.http.services.adguard.loadbalancer.server.port: 3000
      traefik.http.routers.adguard.entrypoints: websecure
      traefik.http.routers.adguard.tls: true
      traefik.http.routers.adguard.tls.certResolver: letsencrypt
