
x-common-other: &other
  mc:
    image: minio/mc
    container_name: mc
    <<: *common
    restart: "no"
    depends_on:
      - minio
    labels:
      traefik.enable: false

  speedtest-tracker:
    container_name: speed
    image: lscr.io/linuxserver/speedtest-tracker:latest
    <<: *common
    environment:
      <<: *env-vars
      DB_CONNECTION: pgsql
      DB_HOST: postgres
      DB_PORT: 5432
      DB_DATABASE: speedtest
      DB_USERNAME: ${DATABASE_USERNAME}
      DB_PASSWORD: ${DATABASE_PASSWORD}
      APP_DEBUG: true
    volumes:
      - config-speedtest:/config
    restart: unless-stopped
    depends_on:
      - postgres
    labels:
      traefik.http.services.speedtest.loadbalancer.server.port: 80
      traefik.http.routers.speedtest.entrypoints: websecure
      traefik.http.routers.speedtest.tls: true
      traefik.http.routers.speedtest.tls.certResolver: letsencrypt
      label.force.update: true

  adguardhome-sync:
    container_name: adguardhome-sync
    image: lscr.io/linuxserver/adguardhome-sync:latest
    <<: *common
    environment:
      <<: *env-vars
      CONFIGFILE: /config/config.yaml
    volumes:
      - config-adguardhome-sync:/config
    labels:
      traefik.http.services.adguardhomesync.loadbalancer.server.port: 8080
      traefik.http.routers.adguardhomesync.entrypoints: websecure
      traefik.http.routers.adguardhomesync.tls: true
      traefik.http.routers.adguardhomesync.tls.certResolver: letsencrypt
      traefik.docker.network: web

