x-common-dns: &dns  
  adguard:
    container_name: adguard
    image: 11notes/adguard
    read_only: true
    <<: *common
    restart: always
    volumes:
      - config-adguard:/adguard/etc
    sysctls:
      net.ipv4.ip_unprivileged_port_start: 53
    labels:
      traefik.http.routers.adguard.rule: Host(`adguard.${DOMAIN}`) && $RESTRICTED
      traefik.http.services.adguard.loadbalancer.server.port: 8443
      traefik.http.routers.adguard.entryPoints: websecure
      traefik.http.routers.adguard.tls: true
      traefik.http.routers.adguard.tls.certResolver: letsencrypt
