
x-common-other: &other
  mc:
    image: minio/mc
    container_name: mc
    <<: *common
    restart: "no"
    depends_on:
      - minio
    labels:
      traefik.enable: false

  speedtest-tracker:
    container_name: speed
    image: ghcr.io/linuxserver/speedtest-tracker:latest
    <<: *common
    environment:
      <<: *env-vars
      DB_CONNECTION: pgsql
      DB_HOST: postgres
      DB_PORT: 5432
      DB_DATABASE: speedtest
      DB_USERNAME: ${DATABASE_USERNAME}
      DB_PASSWORD: ${DATABASE_PASSWORD}
      APP_DEBUG: true
      APP_KEY: ${SPEEDTEST_APP_KEY}
      PUBLIC_DASHBOARD: true
      CACHE_DRIVER: redis
      REDIS_HOST: valkey
      REDIS_PORT: 6379
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      SPEEDTEST_SCHEDULE: "0 */3 * * *"
      PRUNE_RESULTS_OLDER_THAN: 14
      APP_TIMEZONE: ${TIMEZONE}
      DISPLAY_TIMEZONE: ${TIMEZONE}
      APP_URL: https://speed.${DOMAIN}
      ASSET_URL: https://speed.${DOMAIN}
      TRUSTED_PROXIES: ${TRUSTED_IPS}
    volumes:
      - config-speedtest:/config
    depends_on:
      - postgres
      - valkey
    healthcheck:
      test: curl -fSs localhost/api/healthcheck || exit 1
      <<: *healthcheck
    labels:
      traefik.http.routers.speedtest.rule: Host(`speed.${DOMAIN}`) && $RESTRICTED
      traefik.http.services.speedtest.loadbalancer.server.port: 80
      traefik.http.routers.speedtest.entryPoints: websecure
      traefik.http.routers.speedtest.tls: true
      traefik.http.routers.speedtest.tls.certResolver: letsencrypt

  adguardhome-sync:
    container_name: adguardhome-sync
    image: 11notes/adguard-sync
    read_only: true
    <<: *common
    environment:
      <<: *env-vars
    volumes:
      - config-adguardhome-sync:/adguard-sync/etc
    labels:
      traefik.enable: false

