
x-common-other: &other
  mc:
    image: minio/mc
    container_name: mc
    <<: *common
    restart: "no"
    depends_on:
      - minio
    labels:
      traefik.enable: false

  speedtest-tracker:
    container_name: speed
    image: lscr.io/linuxserver/speedtest-tracker:latest
    <<: *common
    environment:
      <<: *env-vars
      DB_CONNECTION: pgsql
      DB_HOST: postgres
      DB_PORT: 5432
      DB_DATABASE: speedtest
      DB_USERNAME: ${DATABASE_USERNAME}
      DB_PASSWORD: ${DATABASE_PASSWORD}
      APP_DEBUG: true
      APP_KEY: ${SPEEDTEST_APP_KEY}
      PUBLIC_DASHBOARD: true
      CACHE_DRIVER: redis
      REDIS_HOST: redis
      REDIS_PORT: 6379
    volumes:
      - config-speedtest:/config
    depends_on:
      - postgres
    healthcheck:
      test: curl -fSs localhost/api/healthcheck || exit 1
      <<: *healthcheck
    labels:
      traefik.http.services.speedtest.loadbalancer.server.port: 80
      traefik.http.routers.speedtest.entrypoints: websecure
      traefik.http.routers.speedtest.tls: true
      traefik.http.routers.speedtest.tls.certResolver: letsencrypt

  adguardhome-sync:
    container_name: adguardhome-sync
    image: lscr.io/linuxserver/adguardhome-sync:latest
    <<: *common
    environment:
      <<: *env-vars
      CONFIGFILE: /config/config.yaml
    volumes:
      - config-adguardhome-sync:/config
    labels:
      traefik.enable: false

